### ISSUE TITLE
Missing name for the floor in gepettoimport.py

### ISSUE THREAD

**Issue by MaximilienNaveau** [Gepetto/gepetto-viewer-corba#79]
Dear all,

I noticed a problem in gepettoimport.py when we create scene with a floor from gepetto viewer.
If we add this floor, then the script generating the blender model call "makeEmpty(objName)" without any
argument.
Then the "gepettoimport.py" called from blender crashes of course.

Best
Max

**Comment by jmirabel** [comment]
The crash and the "makeEmpty" are two different issues.
- "makeEmpty" should be accompagnied with a self explanatory comment on how to solve this.
- the crash may be due to the version of blender you use. Don't use blender from Ubuntu repository. Install it from the website. It is very easy.

Anyway, your best option in my opinion is not to export the floor and to add it manually in blender.

**Comment by jmirabel** [comment]
Actually, the message is not a comment in the script file. It is printed in the standard output of the viewer comment.

If you want to fix it, provide a proper implementation of method `void BlenderGeomWriterVisitor::apply (LeafNodeGround& node)` in `gepetto-viewer/src/blender-geom-writer.cc`. I think it is sufficient to merely create a box, so something similar to the job done in `void BlenderGeomWriterVisitor::apply (LeafNodeBox& node)`
